### ISSUE TITLE
Autoincrement levelcost

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/ASkyBlock-Bugs-N-Features#121] opened 2017-04-15 12:04 UTC
It would be nice an option to increment levelcost depending in your level. The more level you have, the more difficult will be to level up.

**Comment by tastybento** [comment] 2017-04-15 19:29
Yes, I like this idea.

**Comment by Poslovitch** [comment] 2017-04-15 20:02
Duplicate of #21 ;)
So I close this one.

**Closed** 2017-04-15 20:02 UTC
Labels: Duplicate, Feature request
