### ISSUE TITLE
NPE from YAML Save

### ISSUE THREAD

**Issue by JamieSinn** [tastybento/ASkyBlock-Bugs-N-Features#807] opened 2018-06-11 04:09 UTC
https://pastebin.com/raw/Jj6HUzFx

**Comment by tastybento** [comment] 2018-06-11 04:13
Sorry, there's no information in there that I can do anything about. It's all reporting on the server side of things.

**Comment by JamieSinn** [comment] 2018-06-13 00:05
@aikar can you help with this? It caused someone to lose their island.

**Comment by aikar** [comment] 2018-06-13 00:13
looks like a bug with snakeyaml i guess, nothing much i can do there.

**Comment by aikar** [comment] 2018-06-13 00:14
@tastybento I would suggest saving to a temp file instead, and delete the previous and rename temp to new on successful write, to avoid data loss at least.

**Comment by andrewkm** [comment] 2018-06-13 01:09
Yup, can confirm we had someone lose their island completely due to this, and their ASkyBlock/players YML file reverted to default.

In game they were able to **/is warp** - but could not **/is** - to their island. Their user simply had a plain YML file, stating no island, all challenges reverted to false, etc.

Had to grab their file from an older backup, replace it, and restart the server to get their settings back. (Which btw would be nice if this worked with **/asadmin reload** @tastybento)

**Comment by tastybento** [comment] 2018-06-15 10:30
So, just to review - the idea is to instead of saving player YAML files to their usual filenames, to save to a temporary file and then rename it after it has successfully saved to the proper filename.

**Comment by andrewkm** [comment] 2018-06-15 21:41
@Aikar would be best to answer.

**Comment by JamieSinn** [comment] 2018-06-16 21:16
This happened again. Another user lost their data.

**Comment by tastybento** [comment] 2018-06-17 00:57
@JamieSinn Out of interest, what storage system are you using? An SSD or a network drive? I'm adding the temp file thing, but it's not a root cause solution - if file saves are crapping out, then I'd like to know why.

**Comment by JamieSinn** [comment] 2018-06-17 03:58
SSDs

**Comment by tastybento** [comment] 2018-06-18 05:08
Updated release here for testing: https://github.com/tastybento/askyblock/releases/tag/V3.0.8.9f

**Comment by tastybento** [comment] 2018-06-20 00:12
@andrewkm Okay, we're getting closer to the root cause. It looks like your filesystem is not allowing the files to be copied/saved over. Let's see what the full stack trace says. Please use this version and paste the error log:
https://github.com/tastybento/askyblock/releases/tag/v3.0.8.9debug

**Comment by andrewkm** [comment] 2018-06-20 14:13
Now loading up the debug build.
For documentation this was all the errors I got through 29 hours and 58 minutes of up time:
https://pastebin.com/raw/3tJQ7sP1

Will reply again with debug build's results.

**Comment by andrewkm** [comment] 2018-06-20 14:36
@tastybento also not sure if this should be like that but I have a bunch of TMP files now.
https://i.imgur.com/xyZpZia.png

**Comment by tastybento** [comment] 2018-06-20 15:26
Andrew - the issue is that the tmp files (which have a random name) cannot be moved to their final location, e.g., islandnames.yml. 

I'm looking for the stack trace list that will occur beneath the error line. Can you find that and paste it for a few of the errors. Do not parse the console log, I need the raw set of lines. It should look very messy, with lots of debug on it. Thanks.

**Comment by andrewkm** [comment] 2018-06-20 15:27
I just loaded up the debug build about 30 minutes ago @tastybento will need to check in about an hour to see what errors we encountered.

**Comment by tastybento** [comment] 2018-06-20 15:28
Ah, okay! By the way, you can delete all the tmp files. They are not any use right now.

**Comment by andrewkm** [comment] 2018-06-21 13:10
@tastybento results:

https://pastebin.com/raw/Cit2R69H

**Comment by tastybento** [comment] 2018-06-21 17:00
@andrewkm That is not what I expected. That's actually another error where there's some kind of weirdness with the YAML itself. That is extremely weird, but not related to what we are discussing. Are there no errors that start with this kind of text? i.e., where the tmp files are not being able to be copied?

[15:15:42] [Craft Scheduler Thread - 760/ERROR]: [ASkyBlock] Could not save YAML file! plugins\ASkyBlock\yaml1876658940842789384.tmp -> plugins\ASkyBlock\islandnames.yml

By the way, what OS are you using?

**Comment by andrewkm** [comment] 2018-06-21 17:28
@tastybento the OS our SkyBlock instance runs on is Windows Server 2016.

I’ll check the error logs again tonight and see if perhaps we have any regarding the TMP files. The above was the only error I found after 23 hours up time on the debug build.

**Comment by tastybento** [comment] 2018-06-22 04:50
@andrewkm Thanks. Please try this debug build. https://github.com/tastybento/askyblock/releases/tag/v3.0.8.9debug

There are two bugs going on here:

1. An Access Denied Exception
2. A Concurrency exception

It's possible to fix number 2 by making a copy of the Yaml Config before saving sync. What's happening is that in the time that the YAML is being saved, it's being changed elsewhere on another thread (maybe deleted for example). 

For number 1 though, there's not much I can do about that. The file is locked and it isn't possible to write/move the file. This can be because the file is write-protected, or apparently on Windows, it's being viewed in File Explorer. Just looking through some StackExchange posts, it looks like Windows Explorer can make a preview of the file and in the process prevent it from being deleted (which is what happens when the file is being overwritten). So, all I can recommend is: check your file permissions and that the plugin has the right to write files, check that you're not locking this files with other processes, and if all else fails, move to Linux. :-)

**Comment by andrewkm** [comment] 2018-06-22 09:45
@tastybento I will be running your latest debug build shortly to see next results.

When it comes to the OS, for the SkyBlock server specifically, we cannot change it at this time. We have numerous plugins that write to file, two specifically that write to thousands of files for around 7-8 years now with not an issue ever. I would really like to find the culprit here as it has to be something on SkyBlocks end :(

I'm trying to get more information for you but am not sure where to begin. Let's try this, I have been running SkyBlock since April 1st (_yeah we launched on April Fools lmao_) and have just extracted all logs since then on my Desktop to investigate.

Searching for **saveYamlFile** yields:
https://pastebin.com/raw/bng4xbbu

The first error being on May 27th at 11:47am:
https://pastebin.com/raw/907gyMnq
(_Looks to be a server crash we had at the time_).

The second error is similar, also caused by a server crash, so I will skip that one. **Server crash issue has since been fixed**.

June 4th 3:18am is the first time the **com.wasteofplastic.askyblock.util.Util.lambda$saveYamlFile$0** issues begin:
https://pastebin.com/raw/CK3vxmvR

Looking further...

The first instance of ASkyBlock saveYamlFile was running on Paper build 1427 (Previous before this was 1421).

The third instance (**the one I believe we care about**) of ASkyBlock saveYamlFile was running on Paper build 1431 (Previous before this was 1427).

Looking through our plugin change documentation (we log all plugin version changes every single time we do them), we see the following:

The first instance of ASkyBlock saveYamlFile had this change:
https://i.imgur.com/MBhVtl7.png

The third instance (**the one I believe we care about**) of ASkyBlock saveYamlFile had these changes:
https://i.imgur.com/oGfQcIt.png

I mean all I can come up with here is ASkyBlock does **not** like something that has been changed in Paper Build 1421 -> 1430 (_somewhere between that_).

To be honest I'm at a loss here where else to look. If there's anything you want me to search for please let me know, in the meantime I will have your latest Debug build running to see what we get.

**Comment by andrewkm** [comment] 2018-06-22 12:16
@tastybento so what I’m hearing, is that compared to our other plugins, ASkyBlock isn’t writing properly to files via async, it’s supposed to lock a file from any other process to prevent the issue.

@jamiesinn can maybe share more information.

**Comment by tastybento** [comment] 2018-06-22 17:56
@andrewkm I assume that's about locking the file. I've added that so you can try https://github.com/tastybento/askyblock/releases/tag/v3.0.8.9debug

Let's see what happens there.

**Comment by andrewkm** [comment] 2018-06-22 20:05
Loading up the debug build now :)

**Comment by andrewkm** [comment] 2018-06-22 20:58
@tastybento attempted to run your very latest debug build and all hell broke loss lol.
https://gist.githubusercontent.com/andrewkm/64cceb07ddb0afbbc136d4536766b723/raw/f14e25a429404d53edce628a37ac40baa6dedaeb/gistfile1.txt

Reverted back to a previous debug build for now. (**The first one you gave me, as the second one I never had time to load up, and you changed the file to the third one once I got home.** xP)

**Comment by tastybento** [comment] 2018-06-22 21:39
@andrewkm Thanks for your support. Please try the latest version uploaded where I've added debug printout to find out what's going on.  Those are just errors saying that the files cannot be saved and I'd like to know why. Again very weird!

**Comment by andrewkm** [comment] 2018-06-22 22:45
@tastybento 

Tested this one locally, since I'm getting the same results and it's easy to reproduce.
Same thing, as soon as first account logs in, error shoots, on server /stop command everything blows up:
https://gist.githubusercontent.com/andrewkm/4c2cdbe38e7d3538399e7288b1fcaf72/raw/8ef245afde6b7633ce1e173ba46713440dc8a0de/gistfile1.txt

**Comment by tastybento** [comment] 2018-06-23 01:36
Thanks. Can you double check that those files and the player's folder are actually writable by the user that is running the server, i.e., not read-only? As you can see from the error, during the windows move operation, the temp file cannot overwrite the original file because it is read-only. That error is thrown when there is a permission issue writing the file.

```
java.nio.file.AccessDeniedException: plugins\ASkyBlock\yaml6385704799122617595.tmp -> plugins\ASkyBlock\players\8682f534-d227-4096-aa90-0cb2d2349e19.yml
[18:43:37] [Server thread/WARN]: 	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[18:43:37] [Server thread/WARN]: 	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[18:43:37] [Server thread/WARN]: 	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
[18:43:37] [Server thread/WARN]: 	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
[18:43:37] [Server thread/WARN]: 	at java.nio.file.Files.move(Unknown Source)
```
Also, in that latest build, there is no async saving. I removed that, so there's no async weirdness going on.

I've made a build that you can try here: https://github.com/tastybento/askyblock/releases/tag/v3.0.8.9debug
This adds specific checks for permissions issues so it'll tell us if the system thinks the file is read-only or not. Please let me know what you see.

Thanks!

**Comment by andrewkm** [comment] 2018-06-23 03:55
I have just checked the ASkyBlock folder, the players folder and at least a dozen player files from the original errors. All permissions are **100%** correct and I've verified they are the same as with every other plugin that writes to thousands of files on our server setup.

Now going to try your test build...
...
...
...

And here are the results.
User logs in, error thrown, server **/stop**, explosion:
https://gist.githubusercontent.com/andrewkm/291b25acf744a454c2e48420d8450df4/raw/a0ec42b7643e30c5dc5f1ed55b42f55f42a2bca5/gistfile1.txt

**Comment by tastybento** [comment] 2018-06-23 19:18
I notice that all the files are hidden. What happens if they are unhidden?

**Comment by andrewkm** [comment] 2018-06-23 19:41
@tastybento 
Perhaps some more info for you.

Testing on all three environments yields same results here:

- Using PaperSpigot 1468
- Using **only** ASkyBlock debug build.
- ASkyBlock folder deleted with nothing inside. Fresh.
- **NO OTHER PLUGINS**

Player joins, makes an island, disconnects, I shut down server:
https://pastebin.com/raw/w8jzTNu8

**Comment by tastybento** [comment] 2018-06-23 20:08
Okay, thanks for hanging in there and I appreciate your time. I understand it's just this plugin. I've removed all elements of threading from the code which is what I think may be the issue. I'd very much appreciate it if you could try this https://github.com/tastybento/askyblock/releases/tag/v3.0.8.9debug and see how it works for you. If this works as a baseline, then that'll be great.

**Comment by tastybento** [comment] 2018-06-23 23:04
Thanks, that's really helpful. Based on [this](https://stackoverflow.com/questions/33924479/java-nio-file-filesystemexception-the-process-cannot-access-the-file-because-it), I've changed it so that the file is copied and then deleted rather than moved. Please try the updated binary. If that works, then I'll add in async.

**Comment by andrewkm** [comment] 2018-06-23 23:39
@tastybento 

Updated results from latest debug build:
**Once again, fresh test**
https://pastebin.com/raw/9b8wsqtA

**Comment by andrewkm** [comment] 2018-06-23 23:40
Just to ensure I'm running the correct debug build, the file size would be: **913,127 bytes**
Seem correct?

**Comment by tastybento** [comment] 2018-06-24 01:14
Well, I thought we'd solved that with the copy, but clearly the OS thinks the file is open for some reason. Let's try one more thing and then I'm going to have to try and find a Windows machine so I can try and replicate so you're not bothered by these tests!
Version 8 is on the release page. Please try it. I expect an error, but let's see. I just removed all file locking and saving using the Bukkit API (which appears to work). The goal was to try and do the save to a temp file and then move/copy it to the final file, but that doesn't seem to work right now reliably. It may be a Java garbage collection issue, I don't know. Crazy.

**Comment by andrewkm** [comment] 2018-06-24 02:32
@tastybento 

Updated results from latest debug build:
**Fresh test**
https://pastebin.com/raw/a2940F2F

PS: I **100%** don't mind the testing, keep throwing them at me dozens more times. I'll help anyway I can to fix this as it can be a serious killer to servers who don't take backups. (We've already had to restore 4 players that this happened to from our 24 hour backups.)

Also, not sure if the above log but I'm assuming this is good news, looks much cleaner right?

**Comment by tastybento** [comment] 2018-06-24 05:01
Wow, that's good news. Okay, let's push the envelope and see if async works. Please try version 9 and let's see what happens.

**Comment by andrewkm** [comment] 2018-06-24 05:17
@tastybento 

Updated results from latest debug build:
**Fresh test, no plugins (just ASkyBlock[deleted folder] & Vault), latest Spigot**
https://pastebin.com/raw/8VkTn5bu

Updated results from latest debug build:
**Fresh test, no plugins (just ASkyBlock[deleted folder] & Vault), latest PaperSpigot**
https://pastebin.com/raw/WcWt8DLC

Updated results from latest debug build:
**All plugins, full production environment copy, latest PaperSpigot**
_(TMP files deleted from **ASkyBlock/**)_
_(11,558 files remain in **ASkyBlock/players/**)_
https://pastebin.com/raw/ex9nyMW0
(_Only ASkyBlock information in above pastie, as opposed to all info as first two_)

**Comment by andrewkm** [comment] 2018-06-24 06:33
To confirm, would you like me to run Version 10 in production?

**Comment by tastybento** [comment] 2018-06-24 06:35
It's the same as Version 9 but without the debug "saving async" etc, in the console log, so if Ver 9 is running already, you can leave it running to see how it goes. It's your choice. Time for me to sign off, so I'll check in tomorrow PM.

**Comment by andrewkm** [comment] 2018-06-24 16:40
Just threw build 10 into production now (sorry passed out after I got home last night).
Now I guess we wait and see what's up.

**Comment by andrewkm** [comment] 2018-06-24 17:46
@tastybento 

Did a console log search and noticed the following error:
https://gist.githubusercontent.com/andrewkm/652ace5b6ea7560b480f34858fbacaa9/raw/f7b7c123e00908a7b5b637bed884ca6532c80dfe/gistfile1.txt

Noticed it potentially has to do with island resets, so I've tried to reset my island on our live server and can reproduce the issue:
https://gist.githubusercontent.com/andrewkm/e1c8bd11118e92058f1f03636ca77567/raw/0deaa3a62086129bcab984818705b8851e64942d/gistfile1.txt

Please let me know how to proceed and if I should leave this build running in production.
**Debug build 10.**

**Comment by andrewkm** [comment] 2018-06-24 17:47
A full search for **YAML** in logs only shows the above three errors after 1 hour 19 minutes of uptime.
Perhaps something to do directly with island resets now.

**Comment by tastybento** [comment] 2018-06-24 20:19
Thanks. New Build 11 is on the release page.

From the errors reported, it's a concurrency issue. The async processes are hitting each other when trying to save. During an island reset, about 6 different files can be saved, sometimes the same file, so this is the most likely time for concurrency issues.

As we want to have async (that's what kind of started the whole work on this), I've written a FIFO queue that'll process the save requests. You'll see things like this in the logs and the files get saved:

```
[13:12:23 INFO]: Queue size = 5
[13:12:23 INFO]: Queue size = 4
[13:12:23 INFO]: Queue size = 3
[13:12:23 INFO]: Queue size = 2
[13:12:23 INFO]: Queue size = 1
```

What we'll hopefully not see are any errors as the queue is processed. Please give it a quick test on your local machine and do some resets, shutdowns, etc. and things like that to check you see no errors. Thanks.

**Comment by andrewkm** [comment] 2018-06-24 20:29
@tastybento 

Updated results from latest debug build:
**All plugins, full production environment copy, latest PaperSpigot**
_(TMP files not deleted from **ASkyBlock/**)_
_(11,706 files remain in **ASkyBlock/players/**)_
https://pastebin.com/raw/wp9wNPK2
(_Only ASkyBlock information in above pastie, as opposed to all info as first two_)

**Comment by tastybento** [comment] 2018-06-24 21:01
@andrewkm Looking good! Please try it for real.

**Comment by andrewkm** [comment] 2018-06-24 21:16
@tastybento the debug one or the one from your 3.0.8.9 branch:
https://i.imgur.com/9hw7vMH.png
(Build **23**)?

**Comment by tastybento** [comment] 2018-06-25 01:01
Sorry, I missed your question. They are the same. I just committed the changes I made. Either should be fine, but if you haven't already, use Build 24.

**Comment by andrewkm** [comment] 2018-06-26 16:48
@tastybento Build 24 running in production for 22 hours 30 minutes now, zero errors.

**Comment by tastybento** [comment] 2018-06-26 17:53
Yay! Okay, I'm going to tentatively close this and then I'll look at doing a 3.0.8.9 release on the weekend. Thanks for your help.

**Comment by andrewkm** [comment] 2018-06-26 19:31
@tastybento awesome :)
It looks like one player just reported this issue once again:
https://www.ecocitycraft.com/forum/threads/island-lost-glitched.176982/

However I can see his file was still there prior to our restart (when we took out the broken build and inserted the fixed one) so hopefully it's a remainder of the issue while it was broken.

**Comment by andrewkm** [comment] 2018-06-26 19:36
@tastybento 

Bad news, when I responded above that I was running Build 24 in production for 22 hours 30 minutes now, zero errors, **this was incorrect, I'm sorry**

I looked at just _**latest.log**_ when searching for errors.

I should have also looked at **2018-06-25-4.log** which does infact show that one error and lost island:

https://i.imgur.com/RcnwZ6c.png

Error:

https://pastebin.com/raw/D1eYifD1

Guess we gotta open the issue again and keep investigating :(

**Comment by andrewkm** [comment] 2018-06-26 19:59
@tastybento 

Interesting. From all the YAML errors we have had, this is the first **java.io.FileNotFoundException** one. Just searched a month of log files and noticed that.

**Comment by tastybento** [comment] 2018-06-27 01:45
@andrewkm Saving is working fine, but in this case, there was a clash where the OS would not allow file loading while it was being saved. I've uploaded a new version (to the release page and also it should be on Jenkins) that should address this. Please test. Thanks.

**Comment by andrewkm** [comment] 2018-06-27 17:49
@tastybento loading up your latest build now (sorry wasn't around much yesterday)
Just got back to 3 people with missing islands with constant reports like this:
https://www.ecocitycraft.com/forum/threads/island-lost.177008/

Looking at logs its constantly **java.io.FileNotFoundException**.

Anyways, loading up latest build now and hoping for the best!

**Comment by andrewkm** [comment] 2018-06-27 23:38
@tastybento looking good after 6 hours, going to examine for another 24 hours and report back tomorrow afternoon.

**Comment by tastybento** [comment] 2018-06-27 23:59
Thanks. For those players, you should be able to register them back to their islands. You may need to unregister first and then register them back.

**Comment by andrewkm** [comment] 2018-06-28 00:05
@tastybento Their files get completely wiped back to default.
What I do is grab the file from one of my automatic 24 hour backups, and load it up during our next maintenance.

Which I should bring up, changing player files and using **/asadmin reload** is of no use. Thus I must always wait for a server restart to get their files back.

**Comment by andrewkm** [comment] 2018-06-28 18:44
@tastybento looking good for 25 hours now, zero **yaml** errors.

**Comment by andrewkm** [comment] 2018-07-01 19:57
@tastybento 72 hours+
No errors/issues.

**Comment by tastybento** [comment] 2018-07-01 21:34
Phew. I was wary of closing this one again. If you see a need, make a new bug so I don't have to, haha.

**Closed by tastybento** 2018-07-01 21:34 UTC
Labels: Tweak, Under investigation
