### ISSUE TITLE
ASkyBlock 3.0.9.3 leaders NullPointerException

### ISSUE THREAD

**Issue by ClementGF** [tastybento/ASkyBlock-Bugs-N-Features#888] opened 2018-08-02 20:46 UTC
Hello, 
I have lot of NullPointerException error with ASkyBlock version 3.0.9.3 when I do island.getOwner() or isLeader(UUID) and other functions related to leaders even if the player has an island. How fix these errors? This is very problematic because it generates many errors in plugins using ASkyBlock API.

**Comment by tastybento** [comment] 2018-08-03 18:40
I suspect it is due to the owner UUID being set to null. I am trying to understand why this is happening. I think it may be fixed with 3.0.9.4 but I need testers.

**Comment by ClementGF** [comment] 2018-08-03 20:24
I tried your release 3.0.9.4a with a simple verification isLeader(uuid) when a player join the server, i always  obtained false in response while "/asadmin info" give correct leader.

**Comment by tastybento** [comment] 2018-08-03 23:25
I can't replicate this - it works fine in my testing. I'll need to see your code and you should also confirm you are doing this with a clean install of ASkyBlock, i.e., all files deleted beforehand.

**Comment by ClementGF** [comment] 2018-08-04 07:57
I tried again this morning, with isLeader I made a mistake because you consider than player isn't leader if player is alone (which is  counter-intuitive), so i tried with my first problem getOwner and it's corrected. Thank you.

**Comment by tastybento** [comment] 2018-08-04 15:33
Can you confirm if you are doing **/asadmin info** while on the island, or **/asadmin info Heliosard**? They are actually different commands and may give different results.

**Comment by ClementGF** [comment] 2018-08-04 17:25
I did /asadmin info while on the island.

**Comment by Heliosard** [comment] 2018-08-06 10:37
Hello,
The problem is serious, when will we get a valid fix?

Thank you in advance for taking the necessary steps.

**Comment by tastybento** [comment] 2018-08-06 14:50
At least a week if you cannot find the bug yourself in the code and issue a Pull Request. I'm out of the country and cannot work on this right now.

**Comment by Poslovitch** [comment] 2018-08-07 11:35
I'll try to see if I can replicate that one.

**Comment by tastybento** [comment] 2018-08-09 04:40
@ClementGF We can't replicate. Please confirm that you see this issue on a fresh clean install. I suspect your server data files are the issue, so you may need to stop the server, delete islands.yml and restart to get them back in sync.

**Closed** 2018-08-14 03:08 UTC
Labels: Can't replicate, Waiting for response
