### ISSUE TITLE
problem in challenges !!

### ISSUE THREAD

**Issue by seb962** [tastybento/ASkyBlock-Bugs-N-Features#580] opened 2017-12-27 13:11 UTC
hello, I put the plugin AskyBlock worked well, but in doing a mission I did not jump error in the chat, but when doing a challenge does not let you do it you do not get the error or anything like that.
I forgot I do not have, I saw in frequently asked questions and I saw if it helped me so I try it if it stays the same,
Please help me !!

**Comment by tastybento** [comment] 2017-12-27 17:37
I'm sorry, I don't understand. What is the problem?

**Comment by seb962** [comment] 2017-12-27 18:19
good the problem is the challenges, it does not take away the inventory items, it does not give you rewards and it does not mark the challenges in the form of brightness.
It's like the challenge would be disabled.

**Comment by tastybento** [comment] 2017-12-28 20:05
Duplicate of #581

**Closed by tastybento** 2017-12-28 20:05 UTC
Labels: Support request, Waiting for response
