### ISSUE TITLE
Players losing ability to do things with their island.

### ISSUE THREAD

**Issue by AmazedMender16** [tastybento/ASkyBlock-Bugs-N-Features#859] opened 2018-07-14 21:36 UTC
Server version:
git-Spigot-642f6d2-6103339 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

ASkyblock Version:
V3.0.9

This issue started occuring after upgrading from 3.0.8.9

Players are losing their ability to invite/coop players to their island. They only thin they can do is break and place blocks. When you on their island and running /asadmin info it shows its registered to that player, when you want to check if that player has an island it says "player has no island" when you register him back to hes island it all starts working again for a few hours (/asadmin register name).

cant find any error codes in the logs or anything related to this..

**Comment by tastybento** [comment] 2018-07-15 00:54
Possible duplicate of: https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/857

**Comment by tastybento** [comment] 2018-07-15 14:38
@AmazedMender16 "Losing an island" can happen when the islands.yml file doesn't list you as the owner of an island. This can happen because the file wasn't saved properly in the past. The usual way to fix this is just to delete it (it's just a cache) and let it be regenerated by the player files. In the case on the other ticket, the player files were also corrupted (it looks like). That is why SirBlobman saw errors in the logs. 

What OS are you using and did you use a plugin version prior to 3.0.8.9?

**Comment by AmazedMender16** [comment] 2018-07-15 14:40
Linux 4.4.0-130-generic yes i have been using the plugin for over 2 years now

**Comment by tastybento** [comment] 2018-07-15 14:45
Okay, thanks. I just want to clarify the problem:

1. Issue occurs
2. If you type **/asadmin info** when on the island it says that the island is registered to that player
3. If you type **/asadmin info playername** then is says they do not own any island?

Also, can you trace the problem to when something occurs at all? Like doing coop or kicking someone?

Thanks

**Comment by AmazedMender16** [comment] 2018-07-15 14:56
He says he coop someone onto hes island and after it he lost abilities.

/asadmin info showed he was the island owner
/asadmin info showed he didnt own any isands

**Comment by AmazedMender16** [comment] 2018-07-20 20:02
Any more info on this?

Getting more and more players having this issue

**Comment by AmazedMender16** [comment] 2018-07-20 20:11
Rechecked the logs.. Now im seeing the same messages as #857

**Comment by tastybento** [comment] 2018-07-22 02:36
In your answer:

> He says he coop someone onto hes island and after it he lost abilities.
> /asadmin info showed he was the island owner
> /asadmin info showed he didnt own any isands

The last two lines are the same - I'm not sure which one was done with the player's name. I'm guessing the second one.

> Seems like the data is somehow messed up... the /is warps are correctly but when you do /asadmin info it shows complete different coordinates.. not even near the island...

That sounds like the island distance has changed. When you upgraded, did you use the same island distance number? Can you share some examples with numbers? I'm just guessing without actual logs or data.

**Comment by tastybento** [comment] 2018-07-22 20:02
Ok. Well, there's not much I can do right now to help because I don't have any info on the specifics of the problem, and I can't replicate it. Does this happen all the time or just with a few players?

**Comment by tastybento** [comment] 2018-08-09 04:41
This should be fixed with the latest version, so closing for now.

**Closed by tastybento** 2018-08-09 04:41 UTC
Labels: Can't replicate, Under investigation, Waiting for response
