### ISSUE TITLE
Just a bunch of errors

### ISSUE THREAD

**Issue by CoolLord22** [tastybento/ASkyBlock-Bugs-N-Features#169] opened 2017-04-30 13:32 UTC
I've been getting quite a list of errors when teleporting happens, not sure why exactly.

When a player goes to their island from the skyblock world: https://pastebin.com/enR5AmU1
Then every now and then this randomly shows up: https://pastebin.com/PjUc2vRF I thought maybe some of it got cut off, but that's all that shows up in console.

EDIT: As you can tell from the console errors, I'm on version V3.0.6.3. I downgraded to V3.0.6.2 and the errors stopped happening. This leads me to believe the problem is with V3.0.6.3.

**Comment by Poslovitch** [comment] 2017-04-30 15:50
I will have a look

**Comment by CoolLord22** [comment] 2017-04-30 16:32
Thank you!

**Comment by tastybento** [comment] 2017-04-30 20:54
I believe this is fixed by https://github.com/tastybento/askyblock/commit/88c8093dd2099300924c325e1293a126721c2c46

**Comment by tastybento** [comment] 2017-04-30 21:00
Yes, duplicate of https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/163

**Comment by tastybento** [comment] 2017-04-30 21:00
I'll try and get the fixed version out today.

**Closed** 2017-04-30 23:26 UTC
Labels: Bug, Duplicate
