### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by Soldier233** [tastybento/ASkyBlock-Bugs-N-Features#882] opened 2018-07-31 14:45 UTC
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.12.2
**Plugin version:**
V3.0.9.3
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
V3.0.9
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
Some island leaders will sometime and somehow lack permission of their own islands, when they type /is command,plugin will create a new one for them, which annoys my players a lot. I tried to update to the latest version.But the situation still happens sometime,Even though I found that you fixed the bug before in the update log.
**Steps to make this happen**
I have no idea

**Comment by Soldier233** [comment] 2018-07-31 16:46
Here are more information.
The lost data only belongs to the island leader.
And his members' info still shows the leader of the island is him.
Here are the screenshots
![QQ图片20180801004453.jpg](https://i.loli.net/2018/08/01/5b609212916b7.jpg)
![QQ图片20180801004448.jpg](https://i.loli.net/2018/08/01/5b6092129bdde.jpg)

**Comment by Soldier233** [comment] 2018-07-31 16:47
STNS is the island leader
and STNSS is a member

**Comment by tastybento** [comment] 2018-08-01 21:53
Can you try this version to see if it helps?
https://github.com/tastybento/askyblock/releases/tag/3.0.9.4a

This is a random bug, so we're trying to track down what is causing the issue.

**Comment by tastybento** [comment] 2018-08-01 21:53
Likely a duplicate of #884

**Comment by Amazefcc233** [comment] 2018-08-02 05:52
Excuse me.We are using AcidIsland, but the link you gave is to download AskyBlock. Is this normal or is it your mistake?

**Comment by tastybento** [comment] 2018-08-03 18:44
Sorry, I didn't see it was AcidIsland. I'll make a build for AcidIsland for you to test.

**Comment by tastybento** [comment] 2018-08-14 03:09
Please try latest release.

**Closed by tastybento** 2018-08-14 03:09 UTC
Labels: Bug, Duplicate, Under investigation
