### ISSUE TITLE
Islands over 1M levels show incorrectly

### ISSUE THREAD

**Issue by BlameXeno** [tastybento/ASkyBlock-Bugs-N-Features#678] opened 2018-03-17 15:40 UTC
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12.1
**Plugin version:**
3.0.8.2
**What other plugins are you using? (do /plugins and paste here)**
MiniPets, AACBungeeMessages, EasySetSpawn, LiteBansGUI, TopTenHeads, EditableSign, CoreProtect, LuckPerms, SLobby, OpenInv, ClearLag, Chairs, BuycraftX, Votifier, VotingPlugin, FastAsyncWorldEdit, Vault, FastAsyncVoxelSniper, AuctionHouse, ASkyBlock, VoxelSniper, PlayerVaults, WorldEdit, Essentials, SpigotLib, ProtocolLib, Multiverse-Core, Citizens, BankNote, EssentialsKitManager, DiscordSRV, EssentialsChat, PlayerRedirect, Multiverse-Portals, SuperVanish, CustomOreGen, TreysCommandBlocker, HolographicDisplays, HideAndCustomPlugins, WorldGuard, Essentials_KitGUI, AAC, Shop, BungeeTabListPlus, CratesPlus, HolographicScoreboard, AACAdditionPro, LiteBans, SilkSpawners, ConditionalCommands, CrazyEnchantments
**Description of issue. What happened?**
My players have complained after 4 teams achieved an island score over 1 million and their chat prefixes display as xxxxK. For example one of my players has 2.1M island levels and his chat prefix displays [2138.3K] {Player_name} > {Message}
**Steps to make this happen**

1. Get an island over 1,000,000 island levels
2. Have the prefix enabled in EssentialsX
3. It displays 1000K

**What do you think should happen?**
It should switch to 1M

**Comment by Poslovitch** [comment] 2018-03-17 17:25
It is working as intended, it's just that I didn't think there would be islands with such big island levels. Will be fixed in the next version

**Comment by BlameXeno** [comment] 2018-03-18 18:26
Thank you. Would you be able to email me back when the new version is available? And do you have a rough ETA as to when it is being released?

Harry

On 17 Mar 2018, at 17:25, Florian CUNY <notifications@github.com<mailto:notifications@github.com>> wrote:


It is working as intended, it's just that I didn't think there would be islands with such big island levels. Will be fixed in the next version

**Closed** 2018-03-29 03:57 UTC
Labels: Tweak
