### ISSUE TITLE
Named zombie villager despawn

### ISSUE THREAD

**Issue by obiku19** [tastybento/ASkyBlock-Bugs-N-Features#473] opened 2017-09-22 22:25 UTC
An odd issue...
One of my players has created a villager breeder / iron farm on his skyblock. To prevent baby villagers to frees when out of range, he added some zombies and zombie villagers into his breeder. He named them to prevent despawning. Because he complained his named zombies some how disappeared I added zombie_villagers to the mobwhitelist in config and spawned 4 zombie-villagers in his farm. To be extra sure the couldn't despawn, I gave them names too.

Unfortunately they despawned after all... :(

According to multiple stories I read on the net, named mobs shouldn't affect the spawnrate and mobcap and shouldn't despawn either. Why do they in aSkyblock? Am I overlooking something?

Your help is appreciated.

**Comment by tastybento** [comment] 2017-09-29 16:23
What version of the plugin and server are you using? Are you using any other plugin, like Multiverse?
Please share your config.yml (just drag and drop it or a zip of it to this box).

**Comment by obiku19** [comment] 2017-10-06 21:25
Sorry for my late reply.
I'm running Spigot 1.12.1 @121. I do use some other plugins too (worldguard, banmanager, essentials, coreprotect, TopTenHeads, AuctionHouse, SinglePlayerSleep, ShopGUIplus, PermissionsEX

[config.zip](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1363946/config.zip)

**Comment by tastybento** [comment] 2017-11-04 23:17
I found a spot that may be causing mobs to despawn if the "remove monsters when login" option or "remove monsters when /island" option is used. I'll close this for now and see if it helps.

**Comment by obiku19** [comment] 2017-11-05 14:20
OK, I turn loginremovemobs to false for now and see if that fixes the issue for the time being. I'll keep you posted

**Comment by obiku19** [comment] 2017-11-05 14:44
K, first try it failed a bit. he lost 1 named zombie villager. I respawned a new 1 and named it again. We'll see what happens between now and tomorrow.
Btw, your milestone code gave me something to think about.... This same user one time forgot to switch his villager breeder off. Which resulted in to many villagers, which lead to de-spawning of villagers (Villager limit was set to 50 that time). At the end his village breeder stopped working, because his village didn't have enough villagers anymore.
For testing I named his villagers in his villager breeder and started to spawn as many villagers as possible. After villager 51 got alive, 1 villager de-spawned. Also here the named villagers de-spawn.
Of course to many villagers on the skyblock isn't something an admin wants (lag), but de-spawning named villagers.... think that is something that should be solved too.
Hope you can take a look at this. Thanks in advance

**Comment by tastybento** [comment] 2017-11-05 15:35
Try the newer release too.

**Comment by obiku19** [comment] 2017-11-08 08:47
Dang it.... :(
Lost them again. I guess there is something else which causes de-spawning too. Because 3 out of the 4 named zombies didn't de-spawn after disabling "remove monsters when /island". After that I uploaded the latest release and the remaining zombies were not affected. 2 Days all was fine, but this morning, the remaining 3 zombies also de-spawned :(

**Comment by tastybento** [comment] 2017-11-08 21:10
I wonder if they are just dying of old age? There is no entity despawn event to track, but there is an entity death event. Hmm.

**Comment by obiku19** [comment] 2017-11-10 21:58
I didn't see any gray hairs on there heads and didn't see wrinkles on their skins either... (lol)
Hope you can figure it out someway. Good luck. I'll keep tracking this thread

**Comment by obiku19** [comment] 2017-11-18 11:07
An update from my side, named zombies de-spawned again :(
I (admin) used spawn eggs to create new zombies and named them right after that, as soon as I left the island, they de-spawned again.
Time between spawning and de-spawning couldn't be longer then 20 minutes.

**Comment by obiku19** [comment] 2017-12-18 11:27
Tasty, is there any update on this issue?
I'm pulling my hairs out. It frustrates that much. Time after time my named mobs de-spawn. Settings loginremovemobs and islandremovemobs ar both set to false. Strangely my mob-grinder is always empty after returning to my island?

**Comment by tastybento** [comment] 2017-12-18 16:19
Sorry, no, because I've no idea what may be causing it. If it happens so quickly and it is reproducible, then you should remove the plugins one by one until it doesn't happen. Let me know what happens.

**Comment by obiku19** [comment] 2017-12-23 22:48
Tastybento, I removed all plugins except Essentials en permissionsEX
The player wasn't on his island, while I (admin) added new named zombies on his island. I went back to spawn to return back to his island straight away..... All zombies were gone on return.
Also all mobs in his mob-grinder were gone. 
[config.txt](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1584485/config.txt)
Added my config, did I set a setting incorrect?

**Comment by tastybento** [comment] 2017-12-24 17:20
How do you add named zombies? Do you use an anvil and name tag,  or do you use a command? Which command exactly? I'd like to try and replicate.

**Comment by tastybento** [comment] 2017-12-24 17:22
Also, just for completeness, which version of Essentials? I have Essentials v2.0.1-b547.

**Comment by tastybento** [comment] 2017-12-24 17:44
Do you have difficulty set to 0 in server.properties? 

I just tried to replicate and I cannot, sorry. I made a spawn in the island world and a player made a new island (at 20000,20000) and then went to spawn (at 10000,10000). As admin I went to the player's island and used spawn eggs to create 4 zombies. I named 3 of them "zombie1" using a name tag. I then went to spawn (/is spawn) and went back (/asadmin tp player name) and the 4th, unnamed zombie was gone. The named ones were there.
I'm using the latest, most up to date Spigot and only Essentials, ASKyBlock and Vault and PEX. I did a fresh clean install of ASKyBlock and used your config. 

The only possible reason I can think for this is that you have your server set to peaceful. In that case hostile mobs will be removed even if they are named. Check your server.properties file and make sure difficulty is not 0. If it's not that then I'm completely stumped, sorry!

**Closed** 2018-02-16 20:07 UTC
Labels: Monitoring, Under investigation
