### ISSUE TITLE
Unable to break blocks on first /is

### ISSUE THREAD

**Issue by ItsCursed** [tastybento/ASkyBlock-Bugs-N-Features#408] opened 2017-08-10 20:10 UTC
My players have to do /is restart in order to get a working island.
Please add me over Discord **ItsCursed#9760**

_We can discuss more from there_
Or else I got over 20 issues on this.

**Comment by ItsCursed** [comment] 2017-08-12 10:20
I've also changed my spawn-protection to "Zero" but still its not letting players do things.

**Comment by tastybento** [comment] 2017-08-13 02:37
What version of the plugin and server are you using? Can you zip up the ASkyBlock folder and drag and drop it to this ticket so I can look at it?

**Comment by ItsCursed** [comment] 2017-08-13 09:17
[ASkyBlock.zip](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1220372/ASkyBlock.zip)
version: 3.0.6.9 (ASkyBlock)
Spigot - (1.8.8 to 1.12)

**Comment by tastybento** [comment] 2017-08-14 00:48
I can replicate the issue. 

Quick fix: Set "island1:" to "default:" in the schematic section of config.yml. In that section it says that you must have a section called "default:". As you have only one island defined, there will be no GUI. If you want two islands to choose from, create a default definition and also an island1: definition.

**Comment by tastybento** [comment] 2017-08-14 01:13
Quick fix: stop server, remove islands.yml, restart. That should work.

**Comment by tastybento** [comment] 2017-08-14 01:17
The issue is that there is an island in your islands.yml file that is centered at 0,200, but your island distance is set to 400. I suspect this was an island you made when you first started the plugin before changing the island distance to 400. With it sitting there at 0,200, any new island that was made at 0,0 was overlapping this island and clashing (the error was mentioned in the console, but it was not super clear what to do). 
There's no bug here to fix unfortunately so I'll just close the issue.

**Closed by tastybento** 2017-08-14 01:17 UTC
Labels: Under investigation
